alias vi='vim'

## color variables
green="\[\e[1;32m\]"
red="\[\e[1;31m\]"
yellow="\[\e[1;33m\]"
normal="\[\e[0m\]"

##PS1 output
PS1="[$red\u@$green\h$yellow$normal][\W]\\\$ "

alias gp='bash ~/scripts/connect_server.sh gpadmin'
alias root='bash ~/scripts/connect_server.sh root'
alias list='~/scripts/get_host_list.sh'
alias ll='ls -lG'
alias c='bash ~/scripts/run_c_program.sh'
alias km='ssh root@km'
alias home='bash /Users/xsong/scripts/go_to_ubuntu_vm.sh'

### case management ###
# alias sf='perl ~/scripts/case_management.pl -t template'
# alias case_finder='perl ~/scripts/case_management.pl -t find -c'
# alias ir='perl /Users/xsong/scripts/case_management.pl -t ir -l'
# alias ircn='perl /Users/xsong/scripts/case_management.pl -t ir -l cn'
# alias eogs='perl /Users/xsong/scripts/case_management.pl -t eogs'

alias logs='perl /Users/xsong/scripts/case_management.pl -t log -c'
# alias clipboard='killall pboard'
alias report='perl /Users/xsong/scripts/case_management.pl -t case_report'
alias pivnet='export http_proxy="socks5://localhost:1086"; export https_proxy="socks5://localhost:1086"; pivnet'
# alias psql='/Library/PostgreSQL/9.6/bin/psql -p 5432 -h aio1 -U gpadmin'
# alias gcp="ssh '-o ServerAliveInterval=5'  gpadmin@gcp-gp7"
alias logserver="ssh paassupport@tanzu-csp-1.tanzu-gss-labs.vmware.com"
# alias pg="ssh postgres@paf-m"

PATH="/Users/xsong/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/Users/xsong/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/Users/xsong/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/Users/xsong/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/xsong/perl5"; export PERL_MM_OPT;

export PATH=$PATH:~/scripts;

### gcp ###
alias vmlist='gcloud compute instances list | grep "^matt-"'
alias aio='gcloud compute ssh gpadmin@matt-gpdb-aio --zone=asia-east2-a'
alias pg='gcloud compute ssh postgres@matt-pgautofailover-monitor --zone=asia-east2-a'
alias gssh='gcloud compute ssh --zone=asia-east2-a'
alias vmstart='gcloud compute instances start --zone=asia-east2-a'
alias vmstop='gcloud compute instances stop --zone=asia-east2-a'
alias gscp='gcloud compute scp --zone=asia-east2-a '
